### ISSUE TITLE
Installation issue on windows

### ISSUE THREAD

**Issue by sameer-coder** [hyperledger/anoncreds-rs#204]
Hello,

While installing the `@hyperledger/anoncreds-nodejs` package on windows 10 x64 I get the following error
```
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --target_arch=$(node scripts/arch.js)
npm ERR! response status 404 Not Found on https://github.com/hyperledger/anoncreds-rs/releases/download/v0.1.0-dev.15/library-win32-$(node.tar.gz
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
npm ERR! node-pre-gyp info using node@19.2.0 | win32 | x64
npm ERR! node-pre-gyp info check checked for "C:\Projects\anoncreds\node_modules\@hyperledger\anoncreds-nodejs\native\anoncreds.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/hyperledger/anoncreds-rs/releases/download/v0.1.0-dev.15/library-win32-$(node.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/hyperledger/anoncreds-rs/releases/download/v0.1.0-dev.15/library-win32-$(node.tar.gz
```

I think for some reason npm is looking for the package at `https://github.com/hyperledger/anoncreds-rs/releases/download/v0.1.0-dev.15/library-win32-$(node.tar.gz)` while the package is located at 
`https://github.com/hyperledger/anoncreds-rs/releases/download/v0.1.0-dev.15/library-windows-x86_64.tar.gz`

Node version: v19.2
Npm version: 8.19.3

Any help would be appreciated. Thanks

**Comment by blu3beri** [comment]
Can you check it with anoncreds@0.1.0-dev.16? Should be fixed :).

**Comment by sameer-coder** [comment]
Thanks for the super quick response! Tried with anoncreds@0.1.0-dev.16 but still no luck

Error log:
```
npm ERR! code 1
npm ERR! path C:\test\node_modules\@hyperledger\anoncreds-nodejs
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --target_arch=$(node scripts/arch.js) --target_platform=$(node scripts/platform.js)
npm ERR! response status 404 Not Found on https://github.com/hyperledger/anoncreds-rs/releases/download/v0.1.0-dev.16/library-$(node-$(node.tar.gz
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
npm ERR! node-pre-gyp info using node@19.2.0 | win32 | x64
npm ERR! node-pre-gyp info check checked for "C:\test\node_modules\@hyperledger\anoncreds-nodejs\native\anoncreds.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/hyperledger/anoncreds-rs/releases/download/v0.1.0-dev.16/library-$(node-$(node.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/hyperledger/anoncreds-rs/releases/download/v0.1.0-dev.16/library-$(node-$(node.tar.gz
npm ERR! node-pre-gyp ERR! install error
npm ERR! node-pre-gyp ERR! stack Error: response status 404 Not Found on https://github.com/hyperledger/anoncreds-rs/releases/download/v0.1.0-dev.16/library-$(node-$(node.tar.gz
npm ERR! node-pre-gyp ERR! stack     at C:\test\node_modules\@mapbox\node-pre-gyp\lib\install.js:67:15
npm ERR! node-pre-gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.18363
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\test\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--target_arch=$(node" "scripts/arch.js)" "--target_platform=$(node" "scripts/platform.js)"
npm ERR! node-pre-gyp ERR! cwd C:\test\node_modules\@hyperledger\anoncreds-nodejs
npm ERR! node-pre-gyp ERR! node -v v19.2.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10
npm ERR! node-pre-gyp ERR! not ok
```

**Comment by blu3beri** [comment]
Ah there seems to be some issue with the string interpolation: 

```
npm ERR! response status 404 Not Found on https://github.com/hyperledger/anoncreds-rs/releases/download/v0.1.0-dev.16/library-$(node-$(node.tar.gz
```

let me check.

**Comment by blu3beri** [comment]
@sameer-coder can you run the `npm install` or `yarn install` inside a bash evironment? it might be related bash vs powershell.

**Comment by blu3beri** [comment]
Do you get the same issue when installing `aries-askar-nodejs`?

**Comment by sameer-coder** [comment]
Output from `yarn install`

```
yarn install v1.22.19
warning package.json: "test" is also the name of a node core module
info No lockfile found.
warning test@1.0.0: "test" is also the name of a node core module
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[3/4] ⠈ ffi-napi
[-/4] ⠁ waiting...
[-/4] ⠁ waiting...
error C:\test\node_modules\@hyperledger\anoncreds-nodejs: Command failed.
Exit code: 255
Command: node-pre-gyp install --target_arch=$(node scripts/arch.js) --target_platform=$(node scripts/platform.js)
Arguments:
Directory: C:\test\node_modules\@hyperledger\anoncreds-nodejs
Output:
--target_platform was unexpected at this time.
```

**Comment by blu3beri** [comment]
> Still no luck :( Tried with both bash and powershell. Let me know if you need me to run some tests
> 
> ```
> $ npm i
> npm ERR! code 1
> npm ERR! path C:\test\node_modules\@hyperledger\anoncreds-nodejs
> npm ERR! command failed
> npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --target_arch=$(node scripts/arch.js) --target_platform=$(node scripts/platform.js)
> npm ERR! response status 404 Not Found on https://github.com/hyperledger/anoncreds-rs/releases/download/v0.1.0-dev.16/library-$(node-$(node.tar.gz
> npm ERR! node-pre-gyp info it worked if it ends with ok
> npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
> npm ERR! node-pre-gyp info using node@19.2.0 | win32 | x64
> npm ERR! node-pre-gyp info check checked for "C:\test\node_modules\@hyperledger\anoncreds-nodejs\native\anoncreds.node" (not found)
> npm ERR! node-pre-gyp http GET https://github.com/hyperledger/anoncreds-rs/releases/download/v0.1.0-dev.16/library-$(node-$(node.tar.gz
> npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/hyperledger/anoncreds-rs/releases/download/v0.1.0-dev.16/library-$(node-$(node.tar.gz
> npm ERR! node-pre-gyp ERR! install error
> npm ERR! node-pre-gyp ERR! stack Error: response status 404 Not Found on https://github.com/hyperledger/anoncreds-rs/releases/download/v0.1.0-dev.16/library-$(node-$(node.tar.gz
> npm ERR! node-pre-gyp ERR! stack     at C:\test\node_modules\@mapbox\node-pre-gyp\lib\install.js:67:15
> npm ERR! node-pre-gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.18363
> npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Sameer\\Desktop\\2023 Downloads\\test\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--target_arch=$(node" "scripts/arch.js)" "--target_platform=$(node" "scripts/platform.js)"
> npm ERR! node-pre-gyp ERR! cwd C:\test\node_modules\@hyperledger\anoncreds-nodejs
> npm ERR! node-pre-gyp ERR! node -v v19.2.0
> npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10
> npm ERR! node-pre-gyp ERR! not ok
> ```

This still seems to be the output of the powershell / cmd.exe, not bash. Can you give the output of running it in a bash environment (maybe git-bash)?

**Comment by sameer-coder** [comment]
It worked 🎉 

Setting `npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"` and running using `git-bash.exe` did the trick!

`aries-askar-nodejs` still fails with the same message but we can close this issue and I will create a new issue there

You saved my day. Thanks!

**Comment by sameer-coder** [comment]
@blu3beri Thanks a lot for your time!

Would it be possible to please update the version for `indy-vdr-nodejs` as well. Thanks!
